export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  candidate: "/candidate",
  candidateOnboarding: "/candidate/onboarding",
  candidateOnboardingPersonal: "/candidate/onboarding/personal",
  candidateOnboardingSkills: "/candidate/onboarding/skills",
  candidateOnboardingLocation: "/candidate/onboarding/location",
  candidateOnboardingExperience: "/candidate/onboarding/experience",
  candidateOnboardingReview: "/candidate/onboarding/review",
  candidateDashboard: "/candidate/dashboard",
  candidateProfile: "/candidate/profile",
  candidateProfileEdit: "/candidate/profile/edit",
  candidateInterests: "/candidate/interests",
  candidateJobs: "/candidate/jobs",
  candidateMatches: "/candidate/matches",
  candidateMessages: "/candidate/messages",
  candidateDocuments: "/candidate/documents",
  candidateMembership: "/candidate/membership",
  candidateNotifications: "/candidate/notifications",
  employer: "/employer",
  employerOnboarding: "/employer/onboarding",
  employerDashboard: "/employer/dashboard",
  employerProfile: "/employer/profile",
  employerProfileEdit: "/employer/profile/edit",
  employerDocuments: "/employer/documents",
  employerSearch: "/employer/search",
  employerShortlist: "/employer/shortlist",
  employerInterests: "/employer/interests",
  employerMatches: "/employer/matches",
  employerMessages: "/employer/messages",
  employerJobPosts: "/employer/job-posts",
  employerNotifications: "/employer/notifications",
  admin: "/admin",
  adminNotifications: "/admin/notifications",
  accountBlocked: "/account/blocked",
  accountRecovery: "/account/recovery",
  accountConflict: "/account/conflict",
} as const;

export type AppRoute = (typeof routes)[keyof typeof routes];
