import { createServerSupabaseClient } from "@/lib/supabase/server";

export type AnalyticsRange = "today" | "yesterday" | "7d" | "30d" | "month" | "previous-month" | "custom";
export function rangeDates(range: AnalyticsRange, customStart?: string, customEnd?: string) { const now = new Date(); let end = new Date(now); let start = new Date(now); if (range === "custom" && customStart && customEnd) { start = new Date(`${customStart}T00:00:00`); end = new Date(`${customEnd}T00:00:00`); end.setDate(end.getDate() + 1); if (Number.isNaN(start.valueOf()) || Number.isNaN(end.valueOf()) || start >= end) { start = new Date(now); start.setDate(start.getDate() - 29); end = new Date(now); } } else if (range === "today") start.setHours(0, 0, 0, 0); else if (range === "yesterday") { start.setDate(start.getDate() - 1); start.setHours(0, 0, 0, 0); end.setHours(0, 0, 0, 0); } else if (range === "7d") start.setDate(start.getDate() - 6); else if (range === "30d") start.setDate(start.getDate() - 29); else if (range === "month") start = new Date(now.getFullYear(), now.getMonth(), 1); else { start = new Date(now.getFullYear(), now.getMonth() - 1, 1); end = new Date(now.getFullYear(), now.getMonth(), 1); } start.setHours(0, 0, 0, 0); return { start: start.toISOString(), end: end.toISOString() }; }
const date = (value: string) => new Date(value).toLocaleDateString("en-CA", { month: "short", day: "numeric" });
const group = (rows: Array<Record<string, unknown>>, field: string) => Object.entries(rows.reduce<Record<string, number>>((out, row) => { const key = String(row[field] ?? "Unknown"); out[key] = (out[key] ?? 0) + 1; return out; }, {})).map(([label, value]) => ({ label, value })).sort((a,b) => b.value-a.value).slice(0, 8);
export async function loadAnalytics(range: AnalyticsRange, customStart?: string, customEnd?: string) {
  const supabase = await createServerSupabaseClient(); const { start, end } = rangeDates(range, customStart, customEnd);
  const [{ data: events }, { data: sessions }, { data: visitors }, { data: profiles }] = await Promise.all([
    supabase.from("analytics_events").select("id,visitor_id,session_id,user_id,event_name,page_path,metadata,created_at").gte("created_at", start).lt("created_at", end).order("created_at", { ascending: false }).limit(10000),
    supabase.from("analytics_sessions").select("id,visitor_id,user_id,started_at,last_activity_at,landing_page,exit_page,source,medium,campaign,referrer,device_type,browser,os,country,city,page_view_count").gte("started_at", start).lt("started_at", end).order("started_at", { ascending: false }).limit(10000),
    supabase.from("analytics_visitors").select("id,anonymous_id,first_seen_at,last_seen_at,first_source,first_medium,first_campaign,first_referrer,first_landing_page,latest_source,latest_medium,latest_campaign,country,city,linked_user_id,linked_at").gte("first_seen_at", start).lt("first_seen_at", end).order("last_seen_at", { ascending: false }).limit(10000),
    supabase.from("profiles").select("id,full_name,email,role,created_at").gte("created_at", start).lt("created_at", end).in("role", ["candidate", "employer"]).order("created_at", { ascending: false }).limit(10000),
  ]);
  const e = events ?? [], s = sessions ?? [], v = visitors ?? [], p = profiles ?? [];
  const days = new Map<string, { label: string; visitors: Set<string>; sessions: number; pageViews: number; registrations: number }>();
  for (const row of s) { const key = new Date(String(row.started_at)).toISOString().slice(0, 10); const item = days.get(key) ?? { label: date(key), visitors: new Set(), sessions: 0, pageViews: 0, registrations: 0 }; item.visitors.add(String(row.visitor_id)); item.sessions++; item.pageViews += Number(row.page_view_count ?? 0); days.set(key, item); }
  for (const row of e) if (row.event_name === "registration_completed") { const key = new Date(String(row.created_at)).toISOString().slice(0, 10); const item = days.get(key) ?? { label: date(key), visitors: new Set(), sessions: 0, pageViews: 0, registrations: 0 }; item.registrations++; days.set(key, item); }
  const registrations = p.map((row) => ({ ...row, acquisition: v.find((visitor) => visitor.linked_user_id === row.id) }));
  return { range: { start, end }, kpis: { visitors: new Set(s.map((row) => row.visitor_id)).size, sessions: s.length, pageViews: e.filter((row) => row.event_name === "page_view").length, registrations: p.length, candidateRegistrations: p.filter((row) => row.role === "candidate").length, employerRegistrations: p.filter((row) => row.role === "employer").length }, timeline: [...days.entries()].sort(([a],[b]) => a.localeCompare(b)).map(([, item]) => ({ label: item.label, visitors: item.visitors.size, sessions: item.sessions, pageViews: item.pageViews, registrations: item.registrations })), sources: group(s, "source"), pages: group(e.filter((row) => row.event_name === "page_view"), "page_path"), devices: group(s, "device_type"), browsers: group(s, "browser"), countries: group(s, "country"), sessions: s, visitors: v, registrations };
}
