import type { Metadata } from "next";
import { Footer } from "@/components/layout/footer";
import { Header } from "@/components/layout/header";
import { Legal } from "@/components/marketing/legal";
import { MarketingShell, PageHero } from "@/components/marketing/page-hero";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for KAAM, operated by FUSION VENTURES FZ-LLC.",
  alternates: { canonical: "https://www.kaamcareer.com/privacy" },
};

const sections: Array<[string, string]> = [
  ["1. Introduction", "This Privacy Policy explains how KAAM, operated by FUSION VENTURES FZ-LLC, handles personal information when you use the KAAM mobile application and related KAAM services. It applies to the Android application with package identifier com.kaamperfectmatch.kaam_perfect_match and to KAAM services made available by us. KAAM is a hiring and job-matching service for Candidates and Employers. The information we process depends on the account type, the features you use, and the information you choose or need to provide to use those features."],
  ["2. Information We Collect", "Account and authentication information: name, email address, phone number where provided, account and authentication identifiers, role (Candidate or Employer), and authentication/session information. If you choose Google Sign-In, Google provides identity information needed to authenticate your KAAM account. Candidate profile and employment information: profile photo, nationality, gender, date of birth, country, city and other location information you enter; headline, skills, languages, job roles, experience, work preferences, salary expectations, availability, privacy preferences, and profile/resume media paths. Employer and company information: company and contact details, trade-license and verification information where provided, company logo, hiring requirements, and related hiring workflow information. Identity-document information: passport and visa images, document numbers, issue and expiry dates, nationality, date of birth, OCR-extracted fields, and document validation, verification, and review results. Government identification information is sensitive information. Communications and activity information: interests and requests, matches, saved and recently viewed candidates, chat messages, notification events and preferences. Device and technical information: Firebase Cloud Messaging device tokens, device or installation identifiers used for notifications, and authentication, service-operation, and error metadata made available by our service providers."],
  ["3. How We Use Information", "We use information to create and authenticate accounts; create Candidate profiles and Employer/company profiles; provide matching, eligibility, hiring, saved-candidate and recently-viewed features; enable interests, matches and chat; deliver in-app and push notifications; provide support; operate, secure and protect KAAM from misuse; and comply with applicable operational requirements. We use identity documents and extracted information to support Candidate identity verification and eligibility workflows."],
  ["4. Candidate and Employer Visibility", "KAAM makes selected professional Candidate profile information available to eligible Employers according to the application's matching and privacy rules. Selected Employer company and hiring information may be available to Candidates as part of the hiring workflow. Interests, matches, and chat content are available to the applicable participants. Passport and visa images, document numbers, OCR-extracted identity fields, and document review information are stored in private KAAM storage and are not made publicly visible to Employers as part of normal Candidate profile visibility."],
  ["5. Camera and Image Access", "KAAM may request camera access when you choose to capture a profile image or identity document. It may also let you choose an image or document file when you choose to upload profile media or identity documents. KAAM does not use the camera continuously."],
  ["6. Notifications", "KAAM uses Firebase Cloud Messaging to deliver relevant service notifications, such as interests, matches, messages, document updates, and account or service events where enabled. KAAM stores device tokens and notification preferences to support this feature. Notification delivery is subject to your device permissions and KAAM notification preferences."],
  ["7. Service Providers", "We use service providers that process information to operate KAAM: Supabase for authentication, database and storage services; Google for Google Sign-In and Firebase Cloud Messaging; and Azure Document Intelligence through a server-side OCR workflow when identity-document OCR is configured and used. These providers process the information needed to provide their services to KAAM. Provider operational logs, authentication metadata, and service telemetry may be retained under the provider's own applicable policies and configuration."],
  ["8. How Information Is Shared", "KAAM shares information within the service where necessary for matching, hiring, and communication, as described in the Candidate and Employer Visibility section. We also disclose information to the service providers described above when needed for them to provide their services to KAAM. We may disclose information where required to comply with applicable law, respond to valid legal process, protect the security of KAAM or its users, or in connection with a lawful business transaction."],
  ["9. Data Security", "KAAM uses HTTPS for information in transit, authenticated access controls, Supabase Row Level Security, server-side authorization for account deletion, and private storage protections for sensitive documents. These measures are designed to protect information, but no online service can guarantee absolute security."],
  ["10. Data Retention", "We retain KAAM account and service information while it is needed to operate the account and service, subject to the deletion process below. We do not state fixed retention periods here because they depend on the relevant data, service operation, and provider configuration. When an account is deleted, KAAM removes the account and associated active KAAM database records and user-owned storage objects according to the implemented deletion workflow. Provider operational logs, backups, and provider-controlled metadata may be subject to the provider's own retention practices and are not necessarily erased immediately."],
  ["11. Account and Data Deletion", "You can permanently delete a KAAM account in the app through Settings / Login & Security → Delete Account. KAAM requires identity verification, an explicit confirmation, and then signs the account out after deletion. You can also use the public deletion page at https://www.fusionventuresglobal.com/kaam/delete-account. It requires verification of the existing KAAM account email before deletion. Deletion is permanent and removes associated active KAAM data according to the implemented deletion workflow."],
  ["12. Your Choices and Requests", "You can manage certain profile, visibility, and notification settings in KAAM. For privacy questions, account information requests, correction requests where supported, or help with deletion, contact us at info@fusionventuresglobal.com."],
  ["13. Children and Age", "KAAM is intended for users aged 18 years or older and is not intended for individuals under 18."],
  ["14. International Processing", "KAAM uses cloud and service providers that may process information across jurisdictions. We do not identify particular processing locations or transfer mechanisms here because they depend on the applicable provider configuration."],
  ["15. Changes to This Privacy Policy", "We may update this Privacy Policy when KAAM's data practices or service functionality change. The current version will be published on this page with its updated date."],
  ["16. Contact Us", "KAAM is operated by FUSION VENTURES FZ-LLC. For privacy questions or requests, contact info@fusionventuresglobal.com."],
];

export default function PrivacyPage() {
  return <><Header /><main><PageHero eyebrow="Privacy policy" title="Your privacy at KAAM.">This policy describes the current KAAM production data flows and account-deletion behavior. Last updated August 13, 2026.</PageHero><MarketingShell><Legal sections={sections} /></MarketingShell></main><Footer /></>;
}
