"use client";
import { createBrowserSupabaseClient } from "@/lib/supabase/browser";
type EventName = "page_view" | "registration_started" | "registration_completed" | "login" | "candidate_profile_completed" | "employer_profile_completed" | "membership_checkout_started" | "membership_purchased" | "candidate_visibility_enabled" | "contact_clicked";
const visitorKey = "kaam.analytics.visitor", sessionKey = "kaam.analytics.session", touchedKey = "kaam.analytics.session.touched", timeout = 30 * 60 * 1000;
const id = () => crypto.randomUUID();
function get(key: string, storage: Storage) { try { return storage.getItem(key); } catch { return null; } }
function visitor() { const saved = get(visitorKey, localStorage); if (saved) return saved; const next = id(); localStorage.setItem(visitorKey, next); return next; }
function session() { const now = Date.now(), saved = get(sessionKey, sessionStorage), touched = Number(get(touchedKey, sessionStorage) ?? 0); if (saved && now - touched < timeout) { sessionStorage.setItem(touchedKey, String(now)); return saved; } const next = id(); sessionStorage.setItem(sessionKey, next); sessionStorage.setItem(touchedKey, String(now)); return next; }
function browser() { const ua = navigator.userAgent; if (/Edg\//.test(ua)) return "Edge"; if (/Firefox\//.test(ua)) return "Firefox"; if (/Chrome\//.test(ua)) return "Chrome"; if (/Safari\//.test(ua)) return "Safari"; return "Other"; }
function os() { const ua = navigator.userAgent; if (/Android/.test(ua)) return "Android"; if (/iPhone|iPad|iPod/.test(ua)) return "iOS"; if (/Windows/.test(ua)) return "Windows"; if (/Mac OS/.test(ua)) return "macOS"; if (/Linux/.test(ua)) return "Linux"; return "Other"; }
function attribution() { const p = new URLSearchParams(location.search), referrer = document.referrer ? new URL(document.referrer).hostname : ""; return { source: p.get("utm_source") ?? (referrer || "direct"), medium: p.get("utm_medium") ?? (referrer ? "referral" : "none"), campaign: p.get("utm_campaign") ?? "", utm_content: p.get("utm_content") ?? "", utm_term: p.get("utm_term") ?? "", referrer, landing_page: sessionStorage.getItem("kaam.analytics.landing") ?? location.pathname }; }
export function track(eventName: EventName, metadata: Record<string, string | number | boolean | null> = {}) { if (typeof window === "undefined" || navigator.doNotTrack === "1" || /bot|crawler|spider/i.test(navigator.userAgent)) return; try { if (!sessionStorage.getItem("kaam.analytics.landing")) sessionStorage.setItem("kaam.analytics.landing", location.pathname); const details = { ...attribution(), device_type: /Mobi|Android|iPhone/i.test(navigator.userAgent) ? "mobile" : "desktop", browser: browser(), os: os(), screen: `${screen.width}x${screen.height}`, ...metadata }; void createBrowserSupabaseClient().rpc("record_analytics_event", { p_anonymous_id: visitor(), p_session_key: session(), p_event_name: eventName, p_page_path: location.pathname, p_metadata: details, p_event_key: id() }); } catch { /* Never block KAAM. */ } }
export function linkAnalyticsIdentity(role: "candidate" | "employer") { try { void createBrowserSupabaseClient().rpc("link_analytics_identity", { p_anonymous_id: visitor(), p_session_key: session(), p_role: role }); } catch { /* Attribution is best effort. */ } }
